server:
  port: 80

spring:
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db_mikomiko?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: xana
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#    prefix: /WEB-INF/
    servlet:
      content-type: text/html

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql